### ISSUE TITLE
Novità sulla data?

### ISSUE THREAD

**Issue by dagoneye** [merge-it/2018#10]
Abbiamo novità sulla data e sulla location?

**Comment by madbob** [comment]
Data: mi sono orientato sul 24 marzo dopo che mi hanno fatto notare che l'1 aprile e' Pasqua, dunque meglio evitare il 31 marzo.

Location: poiche' le cose stavano andando a rilento con l'universita' ho attivato anche i contatti al politecnico. Vedo ora chi mi da una conferma definitiva per primo.

**Comment by madbob** [comment]
Ok, forse ci siamo.

Saremo alla "Cittadella Politecnica": molto bello, [ampi spazi](http://linuxdaytorino.org/2014/assets/img/photos/fra_d.jpg), [posizione comoda](https://www.openstreetmap.org/?mlat=45.06544&mlon=7.65848#map=17/45.06544/7.65848). Ci abbiamo fatto i Linux Day Torino 2013 e 2014, vedasi [qui](http://linuxdaytorino.org/2013/foto.html) e [qua](http://linuxdaytorino.org/2014/foto.html) le foto per farsi una idea del posto.
Con riferimento a [questa planimetria abbozzata](http://linuxdaytorino.org/2014/assets/img/elements/planimetria.png): l'aula marcata come "LIP" ha tavoli e sgabelli, si presta per una "area lounge" per chiaccherate in piccoli gruppi e per il networking tra aziende proposto da Industria Italiana Software Libero, le altre aule (più "universitarie") per i talk; quelle a destra della planimetria sono [un po' più grandi](http://linuxdaytorino.org/2014/assets/img/photos/24.jpg), l'assemblea Wikimedia (se tenuta in questo contesto) la piazzerei in una di queste.

Data: 24 marzo.

**Comment by marcofromsicily** [comment]
il Miglior Merge di sempre

**Comment by cristianolongo** [comment]
ci sono

**Comment by cristianolongo** [comment]
fatemi sapere se ci sono agevolazioni per l'ospitalità per favore

**Comment by lucadelu** [comment]
@madbob le stanze che possiamo utilizzare sono solo quelle colorate o anche le bianche sotto?

**Comment by madbob** [comment]
@lucadelu tutte, quelle colorate sono quelle che abbiamo usato per il Linux Day ;-)
