### ISSUE TITLE
Dare un nome alla cosa

### ISSUE THREAD

**Issue by ic3d** [merge-it/2018#2]
Da quel che capisco, il nome attuale dell'evento è "merge-it". Un nome parecchio generico, che non richiama in nessun modo chi e cosa. :-) 
Si dovrebbe trovare un nome, un acronimo magari, che richiami in maniera globale tutto il mondo del FOSS Italiano. Al momento mi viene in mente solo una roba:
FOSSIC (Free and Open Source Software Italian Council)
Altre idee?

**Comment by madbob** [comment]
Non fosse che almeno meta' delle community coinvolte non hanno niente a che vedere con il FOSS, ed anzi l'intento e' esattamente quello di unire (_to merge_) realta' diverse che hanno in comune solo l'attitudine alla condivisione digitale.
"Merge", proprio perche' generico, e' un termine sufficientemente comune a tutti. "Merge it" viene letteralmente tradotto in "unisci".

Prima di proporre altre sigle e acronimi, consiglierei di provare a pronunciarli ad alta voce per accertarsi di come suonano.

**Comment by ic3d** [comment]
Credo che "merge-it" sia anche un termine troppo generico. Una roba tipo "open-it"? Dovrebbe essere abbastanza favile da pronunciare, anche per chi non sa l'inglese. ;-)

**Comment by madbob** [comment]
Ah, perché "open" non è generico? È la parola più abusata in assoluto in ambito digitale, trovassimo qualcosa di un pochino più originale...
Temo che procedere a tentoni non sia molto utile.

**Comment by ic3d** [comment]
Il termine "open" accomuna tutte le community coinvolte. Poi vabbè.

**Comment by ic3d** [comment]
Il termine "open" accomuna tutte le community coinvolte. Poi vabbè.

**Comment by emilyalbini** [comment]
[rimosso il commento duplicato]

**Comment by madbob** [comment]
merge-it
