### ISSUE TITLE
Registrare il dominio per il sito web.

### ISSUE THREAD

**Issue by emilyalbini** [merge-it/2018#3]
Direi che, appena formalizzato il nome dell'evento, è il caso di registrare il dominio per evitare di farcelo "scappare".

Bloccato da #2.

**Comment by emilyalbini** [comment]
Se continuiamo con il nome "merge-it", ho dato un'occhiata ai primi domini che mi venivano in mente.

* merge.it: registrato da uno squatter, bisognerà pagare molto mi sa per averlo
* merge-it.org: registrato da un'azienda tedesca (?)
* merge-italy.org: disponibile
* mergeconf.it: disponibile

**Comment by madbob** [comment]
Di merge-it.* ce ne sono liberi a bizzeffe - https://iwantmyname.com/?domain=merge-it
In particolare: .net, .club, .info, .io, .community, .digital
Ci sarebbe anche merge-it.it ma è un tantino cacofonico...

**Comment by emilyalbini** [comment]
Si, ma personalmente preferirei evitare tld strane che non centrano molto con l'evento...

**Comment by madbob** [comment]
merge-it.net
Registrato (al momento e' ancora vuoto) ed aggiunto sui volantini da distribuire in occasione del Linux Day.

**Comment by emilyalbini** [comment]
Se vuoi puoi puntarlo a winter.net.pietroalbini.org, che rimpiazzo merge-it.pietroalbini.org
