### ISSUE TITLE
Abstract "Social Media for Communities"

### ISSUE THREAD

**Issue by ic3d** [merge-it/2018#30]
I social media sono uno strumento sempre più importante per diffondere il messaggio e il "brand", tanto che la popolazione attiva su Facebook, Twitter o Google Plus è più numerosa delle più popolose nazioni del Mondo. I social media hanno sostituito i luoghi di ritrovo tradizionali (bar, cinema, stadio), diventando un enorme luogo di socialità e di incontro, anche casuale. 
Una breve presentazione per capire cos'è il "social media engagement", come funziona e come utilizzarlo al meglio per diffondere il proprio messaggio e cercare di aumentare la partecipazione alle Comunità del Software Libero.

**Comment by madbob** [comment]
Pubblicato https://merge-it.net/talks/social-media-for-communities/
