### ISSUE TITLE
Abstract "Ubuntu Phone, la rinascita"

### ISSUE THREAD

**Issue by ic3d** [merge-it/2018#31]
Ubuntu Touch (conosciuto anche come Ubuntu Phone) è un progetto Open Source sviluppato da Canonical e dalla Comunità Ubuntu che voleva portare un'alternativa libera al mercato di smartphone e tablet, dominato da sistemi proprietari.
Nonostante l'abbandono del progetto da parte di Canonical nel 2017, il progetto è più vivo che mai, con ambiziosi progetti di sviluppo e numerosi dispositivi supportati. 
Ripercorreremo le tappe di questa avventura, mettendone in luce le peculiarità e le novità, e tracciando un possibile sviluppo futuro.

**Comment by madbob** [comment]
Pubblicato - https://merge-it.net/talks/ubuntu-phone-la-rinascita/
