### ISSUE TITLE
Sito.

### ISSUE THREAD

**Issue by madbob** [merge-it/2018#4]
Blocked by #1

**Comment by emilyalbini** [comment]
Vogliamo farlo così HTML nudo?

Per la DUCC-IT avevo creato il sito utilizzando [Lektor](https://www.getlektor.com), che è un generatore statico per siti web (non per blog), con interfaccia web locale per modificare i contenuti (per chi non se la sente di usare l'editor di testo) e tipi di pagina custom.

Se prendessimo come base il sito della DUCC-IT avremmo già [blog](https://www.ducc.it/news), [comunicati stampa](https://www.ducc.it/comunicati) (che alla fine è un secondo blog, Dario li voleva ma si possono anche togliere qua), feed atom per entrambi, [pagine personali dei relatori](https://www.ducc.it/relatori/roberto-guido), [pagine dei talk](https://www.ducc.it/2017/programma/dobbiamo-parlare) e [programma generato dinamicamente dai talk](https://www.ducc.it/2017/programma), tutto questo senza stare a ricreare tutto.

Inoltre, farei in un repo separato il sito (magari merge-it/website?) così si può riutilizzare di anno in anno.

**Comment by emilyalbini** [comment]
Se va bene posso iniziare a togliere tutti i riferimenti alla DUCC-IT dal sito, e caricarlo in un repo qui così possiamo iniziare a modificarlo.

**Comment by madbob** [comment]
Il sito del DUCC-IT lo hai su qualche repository? Almeno per farmi una idea di come sono organizzate le cose...
Immagino che il template cambiera' ancora nel tempo, potenzialmente anche molto: se si riesce a mantenere agevolmente la versione Lektor-izzata bene, altrimenti eviterei di fare (o farti fare) il lavoro di adattamento due volte.

Quando posso preferisco ridisegnare il sito ogni anno (non vale per linuday.it, che adotta il template standard ILS, ma finche' ho mantenuto quello del Linux Day Torino l'ho rifatto ogni anno diverso), ma e' un mero vezzo personale ;-)

**Comment by emilyalbini** [comment]
> Il sito del DUCC-IT lo hai su qualche repository? Almeno per farmi una idea di come sono organizzate le cose...

https://gitlab.com/ducc-it/website

In particolare i contenuti sono (ogni pagina una directory) in `contents/`, la definizione dei modelli in `models/` e i template html in `templates/`.

> Immagino che il template cambiera' ancora nel tempo, potenzialmente anche molto: se si riesce a mantenere agevolmente la versione Lektor-izzata bene, altrimenti eviterei di fare (o farti fare) il lavoro di adattamento due volte.

Beh, alla fine se si cambia lo stile grafico bisogna solo trasportare il CSS e il layout, no?

> Quando posso preferisco ridisegnare il sito ogni anno (non vale per linuday.it, che adotta il template standard ILS, ma finche' ho mantenuto quello del Linux Day Torino l'ho rifatto ogni anno diverso), ma e' un mero vezzo personale ;-)

Il vantaggio di un sito unico è ovviamente che c'è meno lavoro da fare, ma anche che si riesce ad avere il profilo dei relatori con tutti i talk che hanno fatto nei vari anni, magari anche linkando nella pagina di ogni talk la registrazione e le slide. Poi dopo se si vogliono fare aggiustamenti grafici ben vengano :)

**Comment by madbob** [comment]
Si, mi sembra che possa essere gestibile e si possa lavorare direttamente sulla versione Lektor.
Se hai tempo e voglia di forkare il template DUCC-IT ed iniziare ad integrarci dentro il template tanto meglio, sicuramente lo sai fare meglio e prima di me (che sinora non sono andato piu' in la' di Jekylll ;-) ).

Lo terrei comunque sul repository 2018, se e quando sara' necessario un `cp -r` non costa niente.

**Comment by emilyalbini** [comment]
Ok, ho pushato una prima bozza **molto** grezza, ci devo fare ancora alcune modifiche.

Inoltre, nell'attesa che prendiamo il dominio ho configurato un auto-deploy su [merge-it.pietroalbini.org](https://merge-it.pietroalbini.org), quindi ogni modifica al sito pushata dopo qualche minuto sarà visibile sul sito.

**Comment by emilyalbini** [comment]
@madbob è proprio necessario caricare tutto jquery, bootstrap e fontawesome per un sito così semplice? Il template che avevo preparato era almeno leggero e più o meno simile a quello che hai messo di peso, anche se era da completare.

Inoltre, hai completamente rotto [la sezione delle notizie](https://merge-it.pietroalbini.org/news/)...

**Comment by madbob** [comment]
jQuery e Bootstrap sono il minimo sindacale (nel 2017). Magari si potra' eliminare il Javascript di Bootstrap, che non e' effettivamente usato. Almeno per ora.
Il template [della singola news](https://merge-it.pietroalbini.org/news/sito-in-lavorazione/) e' stato allineato di conseguenza, tutto il resto ancora no.

**Comment by emilyalbini** [comment]
Mah, jQuery per buona parte delle cose è inutile se non si vuole garantire un supporto perfetto a browser antichi (e non penso che chi usa Internet Explorer si lamenta se un'animazione non funziona sul nostro sito).

**Comment by emilyalbini** [comment]
Tanto per dire, anche Bootstrap [in futuro smetterà di usare jQuery](https://news.ycombinator.com/item?id=14992269).

**Comment by madbob** [comment]
@pietroalbini suggerimenti su come generare la griglia in homepage a partire dalle descrizioni dei talk?

**Comment by emilyalbini** [comment]
@madbob adesso sono un po incasinato con gli esami, però per la ducc-it avevo [fatto così](https://gitlab.com/ducc-it/website/blob/master/templates/talks.html).

Praticamente, prendo tutte le pagine figlie di talk (che se non è la pagina corrente puoi prendere con `site.get("/talks").children`), le riordino in un dizionario e poi le mostro nella tabella.

Se hai bisogno di una mano vedrò di ritagliare uno spazio nei prossimi giorni.

**Comment by emilyalbini** [comment]
@madbob ok, ho finito gli esami, sei riuscito a generare la tabella o devo guardarci io stasera?

**Comment by madbob** [comment]
Guarda tu, io tra models, templates e contents non son riuscito a capire dove mettere il codice di generazione per la homepage.

**Comment by emilyalbini** [comment]
@madbob  ho caricato sul branch [`generazione-programma`](https://github.com/merge-it/2018/tree/generazione-programma) il codice necessario per generare il programma a partire dai talk. La home page è stata mossa a `templates/home.html`, però non ho aggiunto lo stile (adesso è una semplice lista per ogni sessione): mettilo te come meglio credi :)

**Comment by madbob** [comment]
Alla fine mi sono dovuto arrangiare per fargli generare una griglia decente... Vabbe', e' online.
